import pandas as pd, numpy as np, matplotlib as mpl; mpl.use('Agg'); import matplotlib.pyplot as plt
mpl.rcParams.update({'font.size':8,'axes.labelsize':8,'xtick.labelsize':7,'ytick.labelsize':7,'legend.fontsize':7,'font.family':'Liberation Sans','axes.spines.top':False,'axes.spines.right':False,'axes.linewidth':0.6})
A=pd.read_csv('out/valA.csv'); rng=np.random.default_rng(1)
f,axs=plt.subplots(1,2,figsize=(174/25.4,2.9),gridspec_kw=dict(wspace=0.35))
ax=axs[0]; ax.text(-0.18,1.04,'a',transform=ax.transAxes,fontsize=10,fontweight='bold')
ax.plot([0,32],[0,32],color='grey',lw=0.6,ls=':')
ax.scatter(A.eps*100+rng.uniform(-0.6,0.6,len(A)),A.eps_hat*100,s=10,facecolors='none',edgecolors='k',lw=0.6)
g=A.groupby('eps').eps_hat.agg(['mean','std'])
ax.plot(g.index*100,g['mean']*100,'_',color='k',ms=14,mew=1.5)
ax.set_xlabel('Planted relabelling rate (%)'); ax.set_ylabel('Estimated relabelling rate (%)'); ax.set_xlim(-2,32); ax.set_ylim(-2,32)
ax.set_xticks([0,5,10,20,30]); ax.set_yticks([0,5,10,20,30])
ax=axs[1]; ax.text(-0.18,1.04,'b',transform=ax.transAxes,fontsize=10,fontweight='bold')
ax.plot([0,5.2],[0,5.2],color='grey',lw=0.6,ls=':')
ax.scatter(A.wl,A.wl_hat,s=10,marker='o',facecolors='none',edgecolors='k',lw=0.6,label='Weight on level, $w_L$')
ax.scatter(A.wa,A.wa_hat,s=12,marker='^',color='k',lw=0,label='Weight on achievements, $w_A$')
ax.set_xlabel('Planted weight'); ax.set_ylabel('Recovered weight'); ax.legend(frameon=False,loc='upper left'); ax.set_xlim(0,5.2); ax.set_ylim(0,5.2)
for ext in ['png','tif']: f.savefig(f'dm/Fig1.{ext}',dpi=600,bbox_inches='tight')
f.savefig('dm/Fig1.eps',bbox_inches='tight')
from PIL import Image; im=Image.open('dm/Fig1.png'); im.thumbnail((1500,1500)); im.save('dm/prev1.png')
